/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import crud.DaoEquipo;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Ejecutar;
import modelo.Equipo;
import modelo.TestTeamsFitness;

/**
 *
 * @author elivar
 */
public final class frmFormulario extends javax.swing.JFrame {

    /**
     * Creates new form frmDormulario
     */
    public frmFormulario() {
        initComponents();
        this.setLocation(100, 50);
        ocultarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        btnCargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRanking = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCopas = new javax.swing.JTextField();
        txtGrupo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtp3 = new javax.swing.JTextField();
        txtp2 = new javax.swing.JTextField();
        txtp1 = new javax.swing.JTextField();
        cbx1 = new javax.swing.JComboBox();
        cbx2 = new javax.swing.JComboBox();
        cbx3 = new javax.swing.JComboBox();
        btnEditar = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistEquipos = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALGORITMOS GENÉTICOS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCargar.setLabel("Cargar Equipos");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 149, 39));

        jPanel1.setBackground(new java.awt.Color(35, 174, 59));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Equipo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel1.setText("Id:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtId.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 201, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel2.setText("País:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtPais.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaNumeros(evt);
            }
        });
        jPanel1.add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 201, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel3.setText("Ranking Fifa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtRanking.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtRanking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaSoloNumeros(evt);
            }
        });
        jPanel1.add(txtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 201, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel4.setText("Número de Copas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtCopas.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtCopas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaLetras(evt);
            }
        });
        jPanel1.add(txtCopas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 201, -1));

        txtGrupo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaNumeros(evt);
            }
        });
        jPanel1.add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 201, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel5.setText("Grupo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel7.setText("Partido 1:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel8.setText("Partido 2:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel9.setText("Partido 3:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        txtp3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.add(txtp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 140, -1));

        txtp2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.add(txtp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 140, -1));

        txtp1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.add(txtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 140, -1));

        cbx1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cbx1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                item(evt);
            }
        });
        jPanel1.add(cbx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 150, 30));

        cbx2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cbx2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                item2(evt);
            }
        });
        jPanel1.add(cbx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 150, 30));

        cbx3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cbx3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                item3(evt);
            }
        });
        jPanel1.add(cbx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 36, 790, 197));

        btnEditar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 245, 145, 41));

        btnProcesar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnProcesar.setText("Evaluar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 292, 145, 41));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("POSIBLES EQUIPOS GANADORES DEL MUNDIAL BRASIL 2014");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 550, 30));

        btnGuardar1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 245, 145, 41));

        jPanel2.setBackground(new java.awt.Color(122, 123, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 1, 18))); // NOI18N

        jlistEquipos.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlistEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escogerEquipo(evt);
            }
        });
        jScrollPane1.setViewportView(jlistEquipos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 1, 18))); // NOI18N

        jtxArea.setBackground(java.awt.Color.black);
        jtxArea.setColumns(20);
        jtxArea.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jtxArea.setForeground(java.awt.Color.white);
        jtxArea.setRows(5);
        jScrollPane2.setViewportView(jtxArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 339, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
//        Ejecutar e = new Ejecutar();
//        try {
//            e.ejecutar();
//        } catch (Exception ex) {
//            Logger.getLogger(frmFormulario.class.getName()).log(Level.SEVERE, null, ex);
//        }
        cargarLista();
    }//GEN-LAST:event_btnCargarActionPerformed

    public void ocultarTexto() {
        txtCopas.setEditable(false);
        txtGrupo.setEditable(false);
        txtId.setEditable(false);
        txtPais.setEditable(false);
        txtRanking.setEditable(false);
        txtp1.setEditable(false);
        txtp2.setEditable(false);
        txtp3.setEditable(false);

        cbx1.setEnabled(false);
        cbx2.setEnabled(false);
        cbx3.setEnabled(false);

    }

    public void cargarComboUno(int partido) {
        cbx1.removeAllItems();
        cbx1.addItem(resultado(partido));
        cbx1.addItem("Ganó");
        cbx1.addItem("Perdió");
        cbx1.addItem("Empató");

    }

    public void cargarComboDos(int partido) {
        cbx2.removeAllItems();

        cbx2.addItem(resultado(partido));
        cbx2.addItem("Ganó");
        cbx2.addItem("Perdió");
        cbx2.addItem("Empató");

    }

    public void cargarComboTres(int partido) {
        cbx3.removeAllItems();
        cbx3.addItem(resultado(partido));
        cbx3.addItem("Ganó");
        cbx3.addItem("Perdió");
        cbx3.addItem("Empató");

    }

    public void editarTexto() {
        txtCopas.setEditable(true);
        txtGrupo.setEditable(true);
        txtPais.setEditable(true);
        txtRanking.setEditable(true);
//        txtp1.setEditable(true);
//        txtp2.setEditable(true);
//        txtp3.setEditable(true);
        cbx1.setEnabled(true);
        cbx2.setEnabled(true);
        cbx3.setEnabled(true);
    }

    public void limpiarTexto() {
        txtCopas.setText("");
        txtGrupo.setText("");
        txtPais.setText("");;
        txtRanking.setText("");
        txtId.setText("");
        txtp1.setText("");
        txtp2.setText("");
        txtp3.setText("");
        cbx1.removeAll();
        cbx2.removeAll();
        cbx3.removeAll();
    }

    public int res(String partido) {
        int resultado = 0;
        if (partido.equalsIgnoreCase("Ganó")) {
            resultado = 3;
        } else {
            if (partido.equalsIgnoreCase("Empató")) {
                resultado = 2;
            } else {
                if (partido.equalsIgnoreCase("Perdió")) {
                    resultado = 1;
                }
            }
        }
        return resultado;
    }

    public String resultado(int partido) {
        String resultado = "";
        if (partido == 3) {
            resultado = "Ganó";
        } else {
            if (partido == 2) {
                resultado = "Empató";
            } else {
                if (partido == 1) {
                    resultado = "Perdió";
                }
            }
        }
        return resultado;
    }

    public void cargarLista() {
        List<Equipo> ls = new ArrayList<Equipo>();
        DaoEquipo daoEquipo = new DaoEquipo();

        ls = daoEquipo.listaEquipo(false);
        DefaultListModel modelo = new DefaultListModel();

        for (Equipo equipo : ls) {
            modelo.addElement(equipo.getNombrepais());
        }

        jlistEquipos.setModel(modelo);

    }
    private void escogerEquipo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escogerEquipo
        // TODO add your handling code here:
        ocultarTexto();
        String nombre = (String) jlistEquipos.getSelectedValue();
        List<Equipo> ls = new ArrayList<Equipo>();
        DaoEquipo daoEquipo = new DaoEquipo();
        Equipo equipoSeleccionado = new Equipo();
        ls = daoEquipo.listaEquipo(false);
        for (Equipo equipo : ls) {
            if (equipo.getNombrepais().equals(nombre)) {
                equipoSeleccionado = equipo;
            }
        }
        txtCopas.setText(equipoSeleccionado.getNumerocopasganadas().toString());
        txtId.setText(Integer.toString(equipoSeleccionado.getEquipo()));
        txtPais.setText(equipoSeleccionado.getNombrepais());
        txtRanking.setText(equipoSeleccionado.getRankingfifa().toString());

        txtp1.setText(resultado(equipoSeleccionado.getPartidouno()));

        txtp2.setText(resultado(equipoSeleccionado.getPartidodos()));
        txtp3.setText(resultado(equipoSeleccionado.getPartidotres()));
        cargarComboUno(equipoSeleccionado.getPartidouno());
        cargarComboDos(equipoSeleccionado.getPartidodos());
        cargarComboTres(equipoSeleccionado.getPartidotres());
        txtGrupo.setText(equipoSeleccionado.getGrupo());
            // JOptionPane.showMessageDialog(this, jlistEquipos.getSelectedIndex()+" "+jlistEquipos.getSelectedValue());


    }//GEN-LAST:event_escogerEquipo

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un Equipo de la lista");
        } else {
            editarTexto();
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:

        if (jlistEquipos.getModel().getSize() != 0) {
            TestTeamsFitness test = new TestTeamsFitness();
            try {
                test.initialize();
                test.testSelectFittestTeam();
                jtxArea.setText(test.solucion());
            } catch (Exception ex) {
                Logger.getLogger(frmFormulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay equipos en la lista, primero cargue los equipos");
        }

    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:

        if (txtCopas.getText().equals("") || txtGrupo.getText().equals("") || txtPais.getText().equals("") || txtRanking.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos Vacios, no se puede guardar");

        } else {
            if (txtId.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Los datos no pertenecen a ningún Equipo de la Base de Datos");
            } else {
                Equipo equipo = new Equipo();
                DaoEquipo daoEquipo = new DaoEquipo();
                equipo.setEquipo(Integer.parseInt(txtId.getText()));
                equipo.setNombrepais(txtPais.getText());
                equipo.setPartidodos(res(txtp2.getText()));
                equipo.setPartidouno(res(txtp1.getText()));
                equipo.setPartidotres(res(txtp3.getText()));
                equipo.setNumerocopasganadas(Integer.parseInt(txtCopas.getText()));
                equipo.setRankingfifa(Integer.parseInt(txtRanking.getText()));
                equipo.setGrupo(txtGrupo.getText());
                daoEquipo.editar(equipo);
                JOptionPane.showMessageDialog(this, "Datos guardados");
                cargarLista();
                limpiarTexto();
                ocultarTexto();
            }
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void item(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_item
        // TODO add your handling code here:
        txtp1.setText((String) cbx1.getSelectedItem());
    }//GEN-LAST:event_item

    private void item2(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_item2
        // TODO add your handling code here:
        txtp2.setText((String) cbx2.getSelectedItem());
    }//GEN-LAST:event_item2

    private void item3(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_item3
        // TODO add your handling code here:
        txtp3.setText((String) cbx3.getSelectedItem());
    }//GEN-LAST:event_item3

    private void validaSoloNumeros(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaSoloNumeros
        // TODO add your handling code here:
        char c;
        c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();//ignora el caracter digitado 
        }

    }//GEN-LAST:event_validaSoloNumeros

    private void validaLetras(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaLetras
        // TODO add your handling code here:
        char c;
        c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();//ignora el caracter digitado 
        }
    }//GEN-LAST:event_validaLetras

    private void validaNumeros(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaNumeros
        // TODO add your handling code here:
        char c;
        c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_validaNumeros

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnProcesar;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbx1;
    private javax.swing.JComboBox cbx2;
    private javax.swing.JComboBox cbx3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jlistEquipos;
    private javax.swing.JTextArea jtxArea;
    private javax.swing.JTextField txtCopas;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRanking;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtp2;
    private javax.swing.JTextField txtp3;
    // End of variables declaration//GEN-END:variables
}
